/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Function.ListUsersController;
import Function.MenuController;
import Function.ProfileUsersController;
import Function.RegisterClientController;
import Models.Client;
import Models.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author Fanfo
 */
public class ListUsers extends javax.swing.JFrame {

    User usuario;
    MenuController menu_controller = new MenuController();
    ListUsersController controladorListUsers = new ListUsersController();
    /**
     * Creates new form Menu
     */
    public ListUsers(User u) {
        usuario = u;
        initComponents();
        scaleImage();
        controladorListUsers.nextPage(tablaUsuarios);
    }
    
    public ListUsers() {
        initComponents();
        scaleImage();
        controladorListUsers.nextPage(tablaUsuarios);
    }

    public void scaleImage(){
                
        ImageIcon icon = new ImageIcon("src\\Images\\Login\\FastMobileWhite.png");
        //Escalando para que se acomoden
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(fastMobileWhite.getWidth(),fastMobileWhite.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        fastMobileWhite.setIcon(scaledIcon);   
        
        icon = new ImageIcon("src\\Images\\Login\\userIcon.png");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(userIcon.getWidth(),userIcon.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        userIcon.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TOP = new javax.swing.JPanel();
        fastMobileWhite = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        centroAdmin = new javax.swing.JLabel();
        Separador = new javax.swing.JPanel();
        White = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        centroAdmin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        TOP.setBackground(new java.awt.Color(255, 255, 255));
        TOP.setPreferredSize(new java.awt.Dimension(1024, 100));
        TOP.setLayout(null);

        fastMobileWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/FastMobileWhite.png"))); // NOI18N
        TOP.add(fastMobileWhite);
        fastMobileWhite.setBounds(20, 20, 140, 60);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userIcon.png"))); // NOI18N
        TOP.add(userIcon);
        userIcon.setBounds(920, 20, 60, 60);

        menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(41, 135, 217));
        menu.setText("Menú");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        TOP.add(menu);
        menu.setBounds(850, 40, 50, 20);

        centroAdmin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        centroAdmin.setText("CENTRO DE ADMINISTRACIÓN FAST MOBILE");
        TOP.add(centroAdmin);
        centroAdmin.setBounds(320, 40, 330, 19);

        getContentPane().add(TOP);
        TOP.setBounds(0, 0, 1030, 100);

        Separador.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout SeparadorLayout = new javax.swing.GroupLayout(Separador);
        Separador.setLayout(SeparadorLayout);
        SeparadorLayout.setHorizontalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        SeparadorLayout.setVerticalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Separador);
        Separador.setBounds(0, 100, 1030, 10);

        White.setBackground(new java.awt.Color(255, 255, 255));
        White.setLayout(null);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Nombres", "Apellidos", "e-mail", "Dirección ", "Teléfono ", "Activo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(3).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(4).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(5).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(6).setResizable(false);
        }

        White.add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 920, 250);

        siguiente.setBackground(new java.awt.Color(255, 255, 255));
        siguiente.setForeground(new java.awt.Color(41, 135, 217));
        siguiente.setText("Siguiente página");
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguientenextPage(evt);
            }
        });
        White.add(siguiente);
        siguiente.setBounds(850, 450, 130, 42);

        anterior.setBackground(new java.awt.Color(255, 255, 255));
        anterior.setForeground(new java.awt.Color(41, 135, 217));
        anterior.setText("Página anterior");
        anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriornextPage(evt);
            }
        });
        White.add(anterior);
        anterior.setBounds(60, 450, 130, 42);

        centroAdmin1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        centroAdmin1.setText("Lista de usuarios.");
        White.add(centroAdmin1);
        centroAdmin1.setBounds(60, 130, 287, 20);

        getContentPane().add(White);
        White.setBounds(0, 0, 1030, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        controladorListUsers.goToClientProfile(this, tablaUsuarios.getSelectedRow(),usuario);
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        controladorListUsers.goToMenu(this, usuario);
    }//GEN-LAST:event_menuMouseClicked

    private void siguientenextPage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguientenextPage
        controladorListUsers.nextPage(tablaUsuarios);
    }//GEN-LAST:event_siguientenextPage

    private void anteriornextPage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriornextPage
        controladorListUsers.nextPage(tablaUsuarios);
    }//GEN-LAST:event_anteriornextPage

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        menu.setForeground(new Color(242,229,46));
        menu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        menu.setForeground(new Color(41,135,217));
    }//GEN-LAST:event_menuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Separador;
    private javax.swing.JPanel TOP;
    private javax.swing.JPanel White;
    private javax.swing.JButton anterior;
    private javax.swing.JLabel centroAdmin;
    private javax.swing.JLabel centroAdmin1;
    private javax.swing.JLabel fastMobileWhite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menu;
    private javax.swing.JButton siguiente;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
