/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Function.LoginController;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Sara Maradiago
 */
public class Login extends javax.swing.JFrame {
    
    LoginController login_controller = new LoginController();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        invalidData.setVisible(false);
        //menuWhite.setBackground(new Color(255,255,255,150));
        //LOGIN.setBackground(new Color(255,255,255,0));
        scaleImage();
        this.setTitle("Fast Mobile");
        //Esto de ultimo siempre
    }
    //Gets
    public String getUser(){
        return nombreUsuario.getText();
    }
    
    public String getPassword(){
        return passwordUsuario.getText();
    }
    
    public Boolean getRemember(){
        return rememberMe.isSelected();
    }
    
    public void showError(int error){
        Toolkit.getDefaultToolkit().beep();
        invalidData.setVisible(true);        
        switch(error)
        {
           case 1 :
              invalidData.setText("Los campos no pueden estar vacios");
              break;

           case 2 :
              invalidData.setText("La contraseña es incorrecta");
              break;

           case 3 :
              invalidData.setText("Usuario no ha sido encontrado");
              break;
           case 4 :
              invalidData.setText("El usuario está inactivo");
              break;   
           default : 
              invalidData.setText("Mis programadores no me saben programar");
        }
    }
    
    public void scaleImage(){
        
        ImageIcon icon = new ImageIcon("src\\Images\\Login\\background.jpg");
        //Escalando para que se acomoden
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(background.getWidth(),background.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        background.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Login\\FastMobileWhite.png");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(fastMobileWhite.getWidth(),fastMobileWhite.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        fastMobileWhite.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Login\\userIcon.png");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(userIcon.getWidth(),userIcon.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        userIcon.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Login\\userPassword.png");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(userPassword.getWidth(),userPassword.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        userPassword.setIcon(scaledIcon);
        
                icon = new ImageIcon("src\\Images\\Login\\FastMobileIcon.png");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(fastMobileIcon.getWidth(),fastMobileIcon.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        fastMobileIcon.setIcon(scaledIcon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuWhite = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        passwordUsuario = new javax.swing.JTextField();
        nombreUsuario = new javax.swing.JTextField();
        userIcon = new javax.swing.JLabel();
        userPassword = new javax.swing.JLabel();
        rememberMe = new javax.swing.JCheckBox();
        forgotPassword = new javax.swing.JLabel();
        LOGIN = new javax.swing.JButton();
        fastMobileIcon = new javax.swing.JLabel();
        invalidData = new javax.swing.JLabel();
        TOP = new javax.swing.JPanel();
        fastMobileWhite = new javax.swing.JLabel();
        CENTER = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        menuWhite.setBackground(new java.awt.Color(255, 255, 255));
        menuWhite.setLayout(null);

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bienvenido.setText("BIENVENIDO");
        menuWhite.add(bienvenido);
        bienvenido.setBounds(140, 50, 80, 20);

        passwordUsuario.setText("Contraseña");
        menuWhite.add(passwordUsuario);
        passwordUsuario.setBounds(90, 110, 180, 22);

        nombreUsuario.setText("Nombre de usuario");
        menuWhite.add(nombreUsuario);
        nombreUsuario.setBounds(90, 80, 180, 22);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userIcon.png"))); // NOI18N
        menuWhite.add(userIcon);
        userIcon.setBounds(70, 80, 20, 20);

        userPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userPassword.png"))); // NOI18N
        menuWhite.add(userPassword);
        userPassword.setBounds(70, 110, 20, 20);

        rememberMe.setText("Recuérdame");
        menuWhite.add(rememberMe);
        rememberMe.setBounds(40, 180, 100, 25);

        forgotPassword.setForeground(new java.awt.Color(102, 102, 102));
        forgotPassword.setText("Olvidé mi contraseña");
        menuWhite.add(forgotPassword);
        forgotPassword.setBounds(180, 180, 130, 20);

        LOGIN.setForeground(new java.awt.Color(41, 135, 217));
        LOGIN.setText("LOGIN");
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        menuWhite.add(LOGIN);
        LOGIN.setBounds(120, 210, 110, 30);

        fastMobileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/fastMobileIcon.png"))); // NOI18N
        fastMobileIcon.setPreferredSize(new java.awt.Dimension(10, 10));
        menuWhite.add(fastMobileIcon);
        fastMobileIcon.setBounds(90, 0, 160, 60);

        invalidData.setForeground(new java.awt.Color(255, 0, 0));
        invalidData.setText("Datos inválidos, por favor, intente de nuevo.");
        menuWhite.add(invalidData);
        invalidData.setBounds(50, 150, 240, 16);

        getContentPane().add(menuWhite);
        menuWhite.setBounds(360, 190, 340, 260);

        TOP.setBackground(new java.awt.Color(255, 255, 255));
        TOP.setPreferredSize(new java.awt.Dimension(1024, 100));
        TOP.setLayout(null);

        fastMobileWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/fastMobileWhite.png"))); // NOI18N
        TOP.add(fastMobileWhite);
        fastMobileWhite.setBounds(20, 20, 140, 60);

        getContentPane().add(TOP);
        TOP.setBounds(0, 0, 1030, 100);

        CENTER.setPreferredSize(new java.awt.Dimension(1024, 476));
        CENTER.setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/background.jpg"))); // NOI18N
        CENTER.add(background);
        background.setBounds(0, 0, 1040, 720);

        getContentPane().add(CENTER);
        CENTER.setBounds(-6, -4, 1050, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        try {
            //System.out.println("osi");
            login_controller.letIngreso(this);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CENTER;
    private javax.swing.JButton LOGIN;
    private javax.swing.JPanel TOP;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel fastMobileIcon;
    private javax.swing.JLabel fastMobileWhite;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel invalidData;
    private javax.swing.JPanel menuWhite;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JTextField passwordUsuario;
    private javax.swing.JCheckBox rememberMe;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userPassword;
    // End of variables declaration//GEN-END:variables
}
