/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Function.MenuController;
import Models.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fanfo
 */
public class Menu extends javax.swing.JFrame {

    MenuController menu_controller = new MenuController();
    User usuario;
    /**
     * Creates new form Menu
     */
    public Menu(User u) {
        initComponents();
        scaleImage();
        usuario = u;
        acsexos();
        jLabelFullName.setText(usuario.getPerson().getName()+" "+usuario.getPerson().getLastName());
    }
    
    public Menu() {
        initComponents();
        scaleImage();
    }
    
    public void acsexos(){
        if(!usuario.getRol().getName().equals("Administrador")){
            crearUsuario.setVisible(false);
        }
        if (usuario.getRol().getName().equals("Operador")){
            crearCliente2.setVisible(false);
        }
    }

    public void scaleImage(){
        ImageIcon icon = new ImageIcon("src\\Images\\Menu\\CrearUsuario.jpg");
        //Escalando para que se acomoden
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(crearUsuario_img.getWidth(),crearUsuario_img.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        crearUsuario_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\CrearCliente.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(crearCliente_img.getWidth(),crearCliente_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        crearCliente_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\listaClientes.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(listaClientes_img.getWidth(),listaClientes_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        listaClientes_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\listaUsuarios.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(listaUsuarios_img.getWidth(),listaUsuarios_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        listaUsuarios_img.setIcon(scaledIcon);
                
        icon = new ImageIcon("src\\Images\\Menu\\RegistroPagos.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(registroPagos_img.getWidth(),registroPagos_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        registroPagos_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\cargarPagos.jpeg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(cargarPagos_img.getWidth(),cargarPagos_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        cargarPagos_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\cargarConsumos.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(cargarConsumos_img.getWidth(),cargarConsumos_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        cargarConsumos_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\generarRecibo.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(generarRecibos_img.getWidth(),generarRecibos_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        generarRecibos_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\dashboard.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(dashboard_img.getWidth(),dashboard_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        dashboard_img.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBlue = new javax.swing.JPanel();
        jLabelProfileImage = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        crearUsuario = new javax.swing.JPanel();
        crearUsuario2 = new javax.swing.JPanel();
        textoCrearUsuario = new javax.swing.JLabel();
        CrearUsuario = new javax.swing.JLabel();
        crearUsuario_img = new javax.swing.JLabel();
        crearCliente = new javax.swing.JPanel();
        crearCliente2 = new javax.swing.JPanel();
        CrearCliente = new javax.swing.JLabel();
        textoCrearCliente = new javax.swing.JLabel();
        crearCliente_img = new javax.swing.JLabel();
        listaClientes = new javax.swing.JPanel();
        listaClientes2 = new javax.swing.JPanel();
        ListaDeClientes = new javax.swing.JLabel();
        textoListaClientes = new javax.swing.JLabel();
        listaClientes_img = new javax.swing.JLabel();
        registroPagos1 = new javax.swing.JPanel();
        registroPagos3 = new javax.swing.JPanel();
        listarUsuarios = new javax.swing.JLabel();
        textoRegistroPagos1 = new javax.swing.JLabel();
        listaUsuarios_img = new javax.swing.JLabel();
        registroPagos = new javax.swing.JPanel();
        registroPagos2 = new javax.swing.JPanel();
        registroDePagos = new javax.swing.JLabel();
        textoRegistroPagos = new javax.swing.JLabel();
        registroPagos_img = new javax.swing.JLabel();
        cargarPagos = new javax.swing.JPanel();
        cargarPagos2 = new javax.swing.JPanel();
        textoCrearUsuario1 = new javax.swing.JLabel();
        CargarPagos = new javax.swing.JLabel();
        cargarPagos_img = new javax.swing.JLabel();
        cargarConsumos = new javax.swing.JPanel();
        cargarConsumos2 = new javax.swing.JPanel();
        textoCrearUsuario2 = new javax.swing.JLabel();
        CargarConsumos = new javax.swing.JLabel();
        cargarConsumos_img = new javax.swing.JLabel();
        generarRecibo = new javax.swing.JPanel();
        cargarConsumos3 = new javax.swing.JPanel();
        textoCrearUsuario4 = new javax.swing.JLabel();
        generarRecibos = new javax.swing.JLabel();
        generarRecibos_img = new javax.swing.JLabel();
        verDashboard = new javax.swing.JPanel();
        verDashboard2 = new javax.swing.JPanel();
        textoCrearUsuario3 = new javax.swing.JLabel();
        VerDashboard = new javax.swing.JLabel();
        dashboard_img = new javax.swing.JLabel();
        panelDerecho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 620));
        setPreferredSize(new java.awt.Dimension(1024, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelBlue.setBackground(new java.awt.Color(41, 135, 217));
        jPanelBlue.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanelBlue.setLayout(null);

        jLabelProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userIcon.png"))); // NOI18N
        jLabelProfileImage.setMaximumSize(new java.awt.Dimension(65, 65));
        jLabelProfileImage.setMinimumSize(new java.awt.Dimension(65, 65));
        jLabelProfileImage.setPreferredSize(new java.awt.Dimension(65, 65));
        jPanelBlue.add(jLabelProfileImage);
        jLabelProfileImage.setBounds(20, 20, 65, 65);

        jLabelFullName.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabelFullName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFullName.setText("Eren Jaeger");
        jPanelBlue.add(jLabelFullName);
        jLabelFullName.setBounds(110, 20, 810, 43);

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setText("Perfil");
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToProfile(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilMouseExited(evt);
            }
        });
        jPanelBlue.add(perfil);
        perfil.setBounds(110, 70, 30, 16);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Cerrar sesión");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanelBlue.add(logout);
        logout.setBounds(150, 70, 72, 16);

        getContentPane().add(jPanelBlue);
        jPanelBlue.setBounds(0, 0, 1024, 100);

        panelCentro.setBackground(new java.awt.Color(238, 238, 238));

        crearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuario.setMinimumSize(new java.awt.Dimension(220, 150));
        crearUsuario.setPreferredSize(new java.awt.Dimension(220, 150));
        crearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        crearUsuario2.setLayout(null);

        textoCrearUsuario.setText("Añadir un nuevo usuario.");
        textoCrearUsuario.setPreferredSize(new java.awt.Dimension(180, 16));
        crearUsuario2.add(textoCrearUsuario);
        textoCrearUsuario.setBounds(20, 30, 180, 20);

        CrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseExited(evt);
            }
        });
        crearUsuario2.add(CrearUsuario);
        CrearUsuario.setBounds(20, 10, 120, 20);

        crearUsuario.add(crearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        crearUsuario_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        crearUsuario_img.setMaximumSize(new java.awt.Dimension(65, 65));
        crearUsuario_img.setMinimumSize(new java.awt.Dimension(65, 65));
        crearUsuario_img.setPreferredSize(new java.awt.Dimension(65, 65));
        crearUsuario.add(crearUsuario_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        panelCentro.add(crearUsuario);

        crearCliente.setBackground(new java.awt.Color(255, 255, 255));
        crearCliente.setForeground(new java.awt.Color(255, 255, 255));
        crearCliente.setMinimumSize(new java.awt.Dimension(220, 150));
        crearCliente.setPreferredSize(new java.awt.Dimension(220, 150));
        crearCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearCliente2.setBackground(new java.awt.Color(255, 255, 255));
        crearCliente2.setLayout(null);

        CrearCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearCliente.setText("Crear Cliente");
        CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearClienteMouseExited(evt);
            }
        });
        crearCliente2.add(CrearCliente);
        CrearCliente.setBounds(20, 10, 120, 16);

        textoCrearCliente.setText("Añadir un nuevo cliente.");
        textoCrearCliente.setPreferredSize(new java.awt.Dimension(180, 16));
        crearCliente2.add(textoCrearCliente);
        textoCrearCliente.setBounds(20, 30, 180, 20);

        crearCliente.add(crearCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        crearCliente_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        crearCliente_img.setMaximumSize(new java.awt.Dimension(65, 65));
        crearCliente_img.setMinimumSize(new java.awt.Dimension(65, 65));
        crearCliente_img.setPreferredSize(new java.awt.Dimension(65, 65));
        crearCliente.add(crearCliente_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 160));

        panelCentro.add(crearCliente);

        listaClientes.setBackground(new java.awt.Color(255, 255, 255));
        listaClientes.setForeground(new java.awt.Color(255, 255, 255));
        listaClientes.setMinimumSize(new java.awt.Dimension(220, 150));
        listaClientes.setPreferredSize(new java.awt.Dimension(220, 150));
        listaClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientes2.setBackground(new java.awt.Color(255, 255, 255));
        listaClientes2.setLayout(null);

        ListaDeClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ListaDeClientes.setText("Lista de clientes");
        ListaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseExited(evt);
            }
        });
        listaClientes2.add(ListaDeClientes);
        ListaDeClientes.setBounds(20, 10, 120, 20);

        textoListaClientes.setText("Visualizar clientes.");
        textoListaClientes.setPreferredSize(new java.awt.Dimension(180, 16));
        listaClientes2.add(textoListaClientes);
        textoListaClientes.setBounds(20, 30, 180, 20);

        listaClientes.add(listaClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        listaClientes_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        listaClientes_img.setMaximumSize(new java.awt.Dimension(65, 65));
        listaClientes_img.setMinimumSize(new java.awt.Dimension(65, 65));
        listaClientes_img.setPreferredSize(new java.awt.Dimension(65, 65));
        listaClientes.add(listaClientes_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 216, 160));

        panelCentro.add(listaClientes);

        registroPagos1.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos1.setMinimumSize(new java.awt.Dimension(220, 150));
        registroPagos1.setPreferredSize(new java.awt.Dimension(220, 150));
        registroPagos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroPagos3.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos3.setLayout(null);

        listarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listarUsuarios.setText("Lista de Usuarios");
        listarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listarUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listarUsuariosMouseExited(evt);
            }
        });
        registroPagos3.add(listarUsuarios);
        listarUsuarios.setBounds(20, 10, 120, 16);

        textoRegistroPagos1.setText("Visualizar usuarios.");
        textoRegistroPagos1.setPreferredSize(new java.awt.Dimension(180, 16));
        registroPagos3.add(textoRegistroPagos1);
        textoRegistroPagos1.setBounds(20, 26, 180, 20);

        registroPagos1.add(registroPagos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        listaUsuarios_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        listaUsuarios_img.setMaximumSize(new java.awt.Dimension(65, 65));
        listaUsuarios_img.setMinimumSize(new java.awt.Dimension(65, 65));
        listaUsuarios_img.setPreferredSize(new java.awt.Dimension(65, 65));
        registroPagos1.add(listaUsuarios_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        panelCentro.add(registroPagos1);

        registroPagos.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos.setMinimumSize(new java.awt.Dimension(220, 150));
        registroPagos.setPreferredSize(new java.awt.Dimension(220, 150));
        registroPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroPagos2.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos2.setLayout(null);

        registroDePagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registroDePagos.setText("Registro de pagos");
        registroDePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroDePagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroDePagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroDePagosMouseExited(evt);
            }
        });
        registroPagos2.add(registroDePagos);
        registroDePagos.setBounds(20, 10, 120, 16);

        textoRegistroPagos.setText("Registrar un último pago.");
        textoRegistroPagos.setPreferredSize(new java.awt.Dimension(180, 16));
        registroPagos2.add(textoRegistroPagos);
        textoRegistroPagos.setBounds(20, 30, 180, 20);

        registroPagos.add(registroPagos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        registroPagos_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        registroPagos_img.setMaximumSize(new java.awt.Dimension(65, 65));
        registroPagos_img.setMinimumSize(new java.awt.Dimension(65, 65));
        registroPagos_img.setPreferredSize(new java.awt.Dimension(65, 65));
        registroPagos.add(registroPagos_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        panelCentro.add(registroPagos);

        cargarPagos.setBackground(new java.awt.Color(255, 255, 255));
        cargarPagos.setForeground(new java.awt.Color(255, 255, 255));
        cargarPagos.setMinimumSize(new java.awt.Dimension(220, 150));
        cargarPagos.setPreferredSize(new java.awt.Dimension(220, 150));
        cargarPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarPagos2.setBackground(new java.awt.Color(255, 255, 255));
        cargarPagos2.setLayout(null);

        textoCrearUsuario1.setText("Subir un pago realizado,");
        textoCrearUsuario1.setPreferredSize(new java.awt.Dimension(180, 16));
        cargarPagos2.add(textoCrearUsuario1);
        textoCrearUsuario1.setBounds(20, 30, 180, 16);

        CargarPagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarPagos.setText("Cargar Pagos");
        CargarPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CargarPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CargarPagosMouseExited(evt);
            }
        });
        cargarPagos2.add(CargarPagos);
        CargarPagos.setBounds(20, 10, 120, 20);

        cargarPagos.add(cargarPagos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        cargarPagos_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        cargarPagos_img.setMaximumSize(new java.awt.Dimension(65, 65));
        cargarPagos_img.setMinimumSize(new java.awt.Dimension(65, 65));
        cargarPagos_img.setPreferredSize(new java.awt.Dimension(65, 65));
        cargarPagos.add(cargarPagos_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        panelCentro.add(cargarPagos);

        cargarConsumos.setBackground(new java.awt.Color(255, 255, 255));
        cargarConsumos.setForeground(new java.awt.Color(255, 255, 255));
        cargarConsumos.setMinimumSize(new java.awt.Dimension(220, 150));
        cargarConsumos.setPreferredSize(new java.awt.Dimension(220, 150));
        cargarConsumos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarConsumos2.setBackground(new java.awt.Color(255, 255, 255));
        cargarConsumos2.setLayout(null);

        textoCrearUsuario2.setText("Subir un consumo realizado.");
        textoCrearUsuario2.setPreferredSize(new java.awt.Dimension(180, 16));
        cargarConsumos2.add(textoCrearUsuario2);
        textoCrearUsuario2.setBounds(20, 30, 180, 20);

        CargarConsumos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarConsumos.setText("Cargar Consumos");
        CargarConsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarConsumosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CargarConsumosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CargarConsumosMouseExited(evt);
            }
        });
        cargarConsumos2.add(CargarConsumos);
        CargarConsumos.setBounds(20, 10, 120, 20);

        cargarConsumos.add(cargarConsumos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        cargarConsumos_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        cargarConsumos_img.setMaximumSize(new java.awt.Dimension(65, 65));
        cargarConsumos_img.setMinimumSize(new java.awt.Dimension(65, 65));
        cargarConsumos_img.setPreferredSize(new java.awt.Dimension(65, 65));
        cargarConsumos.add(cargarConsumos_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        panelCentro.add(cargarConsumos);

        generarRecibo.setBackground(new java.awt.Color(255, 255, 255));
        generarRecibo.setForeground(new java.awt.Color(255, 255, 255));
        generarRecibo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarConsumos3.setBackground(new java.awt.Color(255, 255, 255));
        cargarConsumos3.setLayout(null);

        textoCrearUsuario4.setText("Generar un recibo.");
        textoCrearUsuario4.setPreferredSize(new java.awt.Dimension(180, 16));
        cargarConsumos3.add(textoCrearUsuario4);
        textoCrearUsuario4.setBounds(20, 30, 180, 20);

        generarRecibos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generarRecibos.setText("Generar recibos");
        generarRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarRecibosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarRecibosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarRecibosMouseExited(evt);
            }
        });
        cargarConsumos3.add(generarRecibos);
        generarRecibos.setBounds(20, 10, 120, 20);

        generarRecibo.add(cargarConsumos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        generarRecibos_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        generarRecibos_img.setMaximumSize(new java.awt.Dimension(65, 65));
        generarRecibos_img.setMinimumSize(new java.awt.Dimension(65, 65));
        generarRecibos_img.setPreferredSize(new java.awt.Dimension(65, 65));
        generarRecibo.add(generarRecibos_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        panelCentro.add(generarRecibo);

        verDashboard.setBackground(new java.awt.Color(255, 255, 255));
        verDashboard.setForeground(new java.awt.Color(255, 255, 255));
        verDashboard.setMinimumSize(new java.awt.Dimension(220, 150));
        verDashboard.setPreferredSize(new java.awt.Dimension(220, 150));
        verDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verDashboard2.setBackground(new java.awt.Color(255, 255, 255));
        verDashboard2.setLayout(null);

        textoCrearUsuario3.setText("Acceder al dashboard.");
        textoCrearUsuario3.setPreferredSize(new java.awt.Dimension(180, 16));
        verDashboard2.add(textoCrearUsuario3);
        textoCrearUsuario3.setBounds(20, 30, 180, 20);

        VerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VerDashboard.setText("Dashboard");
        VerDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerDashboardMouseExited(evt);
            }
        });
        verDashboard2.add(VerDashboard);
        VerDashboard.setBounds(20, 10, 120, 20);

        verDashboard.add(verDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 60));

        dashboard_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        dashboard_img.setMaximumSize(new java.awt.Dimension(65, 65));
        dashboard_img.setMinimumSize(new java.awt.Dimension(65, 65));
        dashboard_img.setPreferredSize(new java.awt.Dimension(65, 65));
        verDashboard.add(dashboard_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        panelCentro.add(verDashboard);

        getContentPane().add(panelCentro);
        panelCentro.setBounds(0, 100, 800, 480);

        panelDerecho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        getContentPane().add(panelDerecho);
        panelDerecho.setBounds(802, 101, 222, 801);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        perfil.setForeground(new Color(242,229,46));
        perfil.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_perfilMouseEntered

    private void perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseExited
        perfil.setForeground(Color.white);
    }//GEN-LAST:event_perfilMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(242,229,46));
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseExited

    private void CrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseEntered
        CrearUsuario.setForeground(new Color(41,135,217));
        CrearUsuario.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CrearUsuarioMouseEntered

    private void CrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseExited
        CrearUsuario.setForeground(Color.black);
    }//GEN-LAST:event_CrearUsuarioMouseExited

    private void CrearClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseEntered
        CrearCliente.setForeground(new Color(41,135,217));
        CrearCliente.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CrearClienteMouseEntered

    private void CrearClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseExited
        CrearCliente.setForeground(Color.black);
    }//GEN-LAST:event_CrearClienteMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        menu_controller.logOut(this);
    }//GEN-LAST:event_logoutMouseClicked

    private void goToProfile(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToProfile
        // TODO add your handling code here:
        menu_controller.goToProfile(this, usuario);
    }//GEN-LAST:event_goToProfile

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        if(usuario.getRol().getName().equals("Administrador")){ 
            menu_controller.goToRegisterUser(this, usuario); 
        }else{ 
            Toolkit.getDefaultToolkit().beep(); 
            JOptionPane.showMessageDialog( 
                    this,  
                    "Solo los Administradores pueden registrar nuevos usuarios", 
                    "¡¡ ACCESS DENIED !!",  
                    JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_CrearUsuarioMouseClicked

    private void CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseClicked
        if(!usuario.getRol().getName().equals("Operador")){ 
            menu_controller.goToRegisterClient(this, usuario); 
        }else{ 
            Toolkit.getDefaultToolkit().beep(); 
            JOptionPane.showMessageDialog( 
                    this,  
                    "Los Operadores no pueden registrar nuevos Clienes", 
                    "¡¡ ACCESS DENIED !!",  
                    JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_CrearClienteMouseClicked

    private void ListaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseClicked
        menu_controller.goToListClients(this, usuario);
    }//GEN-LAST:event_ListaDeClientesMouseClicked

    private void ListaDeClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseEntered
        ListaDeClientes.setForeground(new Color(41,135,217));
        ListaDeClientes.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ListaDeClientesMouseEntered

    private void ListaDeClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseExited
        ListaDeClientes.setForeground(Color.black);
    }//GEN-LAST:event_ListaDeClientesMouseExited

    private void registroDePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseClicked
        menu_controller.goToPaymentRegister(this, usuario);
    }//GEN-LAST:event_registroDePagosMouseClicked

    private void registroDePagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseEntered
        registroDePagos.setForeground(new Color(41,135,217));
        registroDePagos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registroDePagosMouseEntered

    private void registroDePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseExited
        registroDePagos.setForeground(Color.black);
    }//GEN-LAST:event_registroDePagosMouseExited

    private void listarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarUsuariosMouseClicked
        menu_controller.goToListUsers(this, usuario);
    }//GEN-LAST:event_listarUsuariosMouseClicked

    private void listarUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarUsuariosMouseEntered
        listarUsuarios.setForeground(new Color(41,135,217)); 
        listarUsuarios.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_listarUsuariosMouseEntered

    private void listarUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarUsuariosMouseExited
        listarUsuarios.setForeground(Color.black);
    }//GEN-LAST:event_listarUsuariosMouseExited

    private void CargarPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarPagosMouseClicked
        // TODO add your handling code here:
        menu_controller.goToPaymentsLoad(this, usuario);
    }//GEN-LAST:event_CargarPagosMouseClicked

    private void CargarPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarPagosMouseEntered
        // TODO add your handling code here:
        CargarPagos.setForeground(new Color(41,135,217)); 
        CargarPagos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CargarPagosMouseEntered

    private void CargarPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarPagosMouseExited
        // TODO add your handling code here:
        CargarPagos.setForeground(Color.black);
    }//GEN-LAST:event_CargarPagosMouseExited

    private void CargarConsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarConsumosMouseClicked
        menu_controller.goToConsumeLoad(this, usuario);
    }//GEN-LAST:event_CargarConsumosMouseClicked

    private void CargarConsumosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarConsumosMouseEntered
        CargarConsumos.setForeground(new Color(41,135,217)); 
        CargarConsumos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CargarConsumosMouseEntered

    private void CargarConsumosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarConsumosMouseExited
        CargarConsumos.setForeground(Color.black);
    }//GEN-LAST:event_CargarConsumosMouseExited

    private void VerDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerDashboardMouseClicked
        menu_controller.goToDashboard();
    }//GEN-LAST:event_VerDashboardMouseClicked

    private void VerDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerDashboardMouseEntered
        VerDashboard.setForeground(new Color(41,135,217));  
        VerDashboard.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_VerDashboardMouseEntered

    private void VerDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerDashboardMouseExited
        VerDashboard.setForeground(Color.black);
    }//GEN-LAST:event_VerDashboardMouseExited

    private void generarRecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarRecibosMouseClicked
        menu_controller.goToGenerateReceipt(this, usuario);
    }//GEN-LAST:event_generarRecibosMouseClicked

    private void generarRecibosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarRecibosMouseEntered
        generarRecibos.setForeground(new Color(41,135,217)); 
        generarRecibos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_generarRecibosMouseEntered

    private void generarRecibosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarRecibosMouseExited
        generarRecibos.setForeground(Color.black);
    }//GEN-LAST:event_generarRecibosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CargarConsumos;
    private javax.swing.JLabel CargarPagos;
    private javax.swing.JLabel CrearCliente;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JLabel ListaDeClientes;
    private javax.swing.JLabel VerDashboard;
    private javax.swing.JPanel cargarConsumos;
    private javax.swing.JPanel cargarConsumos2;
    private javax.swing.JPanel cargarConsumos3;
    private javax.swing.JLabel cargarConsumos_img;
    private javax.swing.JPanel cargarPagos;
    private javax.swing.JPanel cargarPagos2;
    private javax.swing.JLabel cargarPagos_img;
    private javax.swing.JPanel crearCliente;
    private javax.swing.JPanel crearCliente2;
    private javax.swing.JLabel crearCliente_img;
    private javax.swing.JPanel crearUsuario;
    private javax.swing.JPanel crearUsuario2;
    private javax.swing.JLabel crearUsuario_img;
    private javax.swing.JLabel dashboard_img;
    private javax.swing.JPanel generarRecibo;
    private javax.swing.JLabel generarRecibos;
    private javax.swing.JLabel generarRecibos_img;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelProfileImage;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel listaClientes;
    private javax.swing.JPanel listaClientes2;
    private javax.swing.JLabel listaClientes_img;
    private javax.swing.JLabel listaUsuarios_img;
    private javax.swing.JLabel listarUsuarios;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JLabel perfil;
    private javax.swing.JLabel registroDePagos;
    private javax.swing.JPanel registroPagos;
    private javax.swing.JPanel registroPagos1;
    private javax.swing.JPanel registroPagos2;
    private javax.swing.JPanel registroPagos3;
    private javax.swing.JLabel registroPagos_img;
    private javax.swing.JLabel textoCrearCliente;
    private javax.swing.JLabel textoCrearUsuario;
    private javax.swing.JLabel textoCrearUsuario1;
    private javax.swing.JLabel textoCrearUsuario2;
    private javax.swing.JLabel textoCrearUsuario3;
    private javax.swing.JLabel textoCrearUsuario4;
    private javax.swing.JLabel textoListaClientes;
    private javax.swing.JLabel textoRegistroPagos;
    private javax.swing.JLabel textoRegistroPagos1;
    private javax.swing.JPanel verDashboard;
    private javax.swing.JPanel verDashboard2;
    // End of variables declaration//GEN-END:variables
}
