/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Function.MenuController;
import Models.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Fanfo
 */
public class Menu extends javax.swing.JFrame {

    MenuController menu_controller = new MenuController();
    User usuario;
    /**
     * Creates new form Menu
     */
    public Menu(User u) {
        initComponents();
        scaleImage();
        usuario = u;
        jLabelFullName.setText(usuario.getPerson().getName()+" "+usuario.getPerson().getLastName());
    }
    
    public Menu() {
        initComponents();
        scaleImage();
    }

    public void scaleImage(){
        ImageIcon icon = new ImageIcon("src\\Images\\Menu\\CrearUsuario.jpg");
        //Escalando para que se acomoden
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(crearUsuario_img.getWidth(),crearUsuario_img.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        crearUsuario_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\CrearCliente.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(crearCliente_img.getWidth(),crearCliente_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        crearCliente_img.setIcon(scaledIcon);
        
        icon = new ImageIcon("src\\Images\\Menu\\RegistroPagos.jpg");
        //Escalando para que se acomoden
        img = icon.getImage();
        imgScale = img.getScaledInstance(listaClientes_img.getWidth(),listaClientes_img.getHeight(),Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgScale);
        listaClientes_img.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBlue = new javax.swing.JPanel();
        jLabelProfileImage = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        crearUsuario = new javax.swing.JPanel();
        crearUsuario2 = new javax.swing.JPanel();
        textoCrearUsuario = new javax.swing.JLabel();
        CrearUsuario = new javax.swing.JLabel();
        crearUsuario_img = new javax.swing.JLabel();
        crearCliente = new javax.swing.JPanel();
        crearCliente2 = new javax.swing.JPanel();
        CrearCliente = new javax.swing.JLabel();
        textoCrearCliente = new javax.swing.JLabel();
        crearCliente_img = new javax.swing.JLabel();
        listaClientes = new javax.swing.JPanel();
        listaClientes2 = new javax.swing.JPanel();
        ListaDeClientes = new javax.swing.JLabel();
        textoListaClientes = new javax.swing.JLabel();
        listaClientes_img = new javax.swing.JLabel();
        registroPagos = new javax.swing.JPanel();
        registroPagos2 = new javax.swing.JPanel();
        registroDePagos = new javax.swing.JLabel();
        textoRegistroPagos = new javax.swing.JLabel();
        registroPagos_img = new javax.swing.JLabel();
        panelDerecho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelBlue.setBackground(new java.awt.Color(41, 135, 217));
        jPanelBlue.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanelBlue.setLayout(null);

        jLabelProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/userIcon.png"))); // NOI18N
        jLabelProfileImage.setMaximumSize(new java.awt.Dimension(65, 65));
        jLabelProfileImage.setMinimumSize(new java.awt.Dimension(65, 65));
        jLabelProfileImage.setPreferredSize(new java.awt.Dimension(65, 65));
        jPanelBlue.add(jLabelProfileImage);
        jLabelProfileImage.setBounds(20, 20, 65, 65);

        jLabelFullName.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabelFullName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFullName.setText("Eren Jaeger");
        jPanelBlue.add(jLabelFullName);
        jLabelFullName.setBounds(110, 20, 810, 43);

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setText("Perfil");
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToProfile(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilMouseExited(evt);
            }
        });
        jPanelBlue.add(perfil);
        perfil.setBounds(110, 70, 30, 16);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Cerrar sesión");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanelBlue.add(logout);
        logout.setBounds(150, 70, 72, 16);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Back.png"))); // NOI18N
        back.setMaximumSize(new java.awt.Dimension(65, 65));
        back.setMinimumSize(new java.awt.Dimension(65, 65));
        back.setPreferredSize(new java.awt.Dimension(65, 65));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        jPanelBlue.add(back);
        back.setBounds(940, 30, 50, 50);

        getContentPane().add(jPanelBlue);
        jPanelBlue.setBounds(0, 0, 1024, 100);

        panelCentro.setBackground(new java.awt.Color(238, 238, 238));

        crearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuario.setLayout(null);

        crearUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        crearUsuario2.setLayout(null);

        textoCrearUsuario.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut libero nec magna</html>");
        textoCrearUsuario.setPreferredSize(new java.awt.Dimension(180, 16));
        crearUsuario2.add(textoCrearUsuario);
        textoCrearUsuario.setBounds(20, 30, 180, 16);

        CrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseExited(evt);
            }
        });
        crearUsuario2.add(CrearUsuario);
        CrearUsuario.setBounds(20, 10, 120, 20);

        crearUsuario.add(crearUsuario2);
        crearUsuario2.setBounds(0, 100, 220, 60);

        crearUsuario_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        crearUsuario_img.setMaximumSize(new java.awt.Dimension(65, 65));
        crearUsuario_img.setMinimumSize(new java.awt.Dimension(65, 65));
        crearUsuario_img.setPreferredSize(new java.awt.Dimension(65, 65));
        crearUsuario.add(crearUsuario_img);
        crearUsuario_img.setBounds(0, 0, 220, 150);

        crearCliente.setBackground(new java.awt.Color(255, 255, 255));
        crearCliente.setForeground(new java.awt.Color(255, 255, 255));
        crearCliente.setLayout(null);

        crearCliente2.setBackground(new java.awt.Color(255, 255, 255));
        crearCliente2.setLayout(null);

        CrearCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearCliente.setText("Crear Cliente");
        CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearClienteMouseExited(evt);
            }
        });
        crearCliente2.add(CrearCliente);
        CrearCliente.setBounds(20, 10, 120, 16);

        textoCrearCliente.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut libero nec magna</html>");
        textoCrearCliente.setPreferredSize(new java.awt.Dimension(180, 16));
        crearCliente2.add(textoCrearCliente);
        textoCrearCliente.setBounds(20, 30, 180, 16);

        crearCliente.add(crearCliente2);
        crearCliente2.setBounds(0, 100, 220, 60);

        crearCliente_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        crearCliente_img.setMaximumSize(new java.awt.Dimension(65, 65));
        crearCliente_img.setMinimumSize(new java.awt.Dimension(65, 65));
        crearCliente_img.setPreferredSize(new java.awt.Dimension(65, 65));
        crearCliente.add(crearCliente_img);
        crearCliente_img.setBounds(0, 0, 216, 160);

        listaClientes.setBackground(new java.awt.Color(255, 255, 255));
        listaClientes.setForeground(new java.awt.Color(255, 255, 255));
        listaClientes.setLayout(null);

        listaClientes2.setBackground(new java.awt.Color(255, 255, 255));
        listaClientes2.setLayout(null);

        ListaDeClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ListaDeClientes.setText("Lista de clientes");
        ListaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListaDeClientesMouseExited(evt);
            }
        });
        listaClientes2.add(ListaDeClientes);
        ListaDeClientes.setBounds(20, 10, 120, 20);

        textoListaClientes.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut libero nec magna</html>");
        textoListaClientes.setPreferredSize(new java.awt.Dimension(180, 16));
        listaClientes2.add(textoListaClientes);
        textoListaClientes.setBounds(20, 30, 180, 16);

        listaClientes.add(listaClientes2);
        listaClientes2.setBounds(0, 100, 220, 60);

        listaClientes_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        listaClientes_img.setMaximumSize(new java.awt.Dimension(65, 65));
        listaClientes_img.setMinimumSize(new java.awt.Dimension(65, 65));
        listaClientes_img.setPreferredSize(new java.awt.Dimension(65, 65));
        listaClientes.add(listaClientes_img);
        listaClientes_img.setBounds(0, 0, 216, 160);

        registroPagos.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos.setLayout(null);

        registroPagos2.setBackground(new java.awt.Color(255, 255, 255));
        registroPagos2.setLayout(null);

        registroDePagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registroDePagos.setText("Registro de pagos");
        registroDePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroDePagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroDePagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroDePagosMouseExited(evt);
            }
        });
        registroPagos2.add(registroDePagos);
        registroDePagos.setBounds(20, 10, 120, 16);

        textoRegistroPagos.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut libero nec magna</html>");
        textoRegistroPagos.setPreferredSize(new java.awt.Dimension(180, 16));
        registroPagos2.add(textoRegistroPagos);
        textoRegistroPagos.setBounds(20, 36, 180, 10);

        registroPagos.add(registroPagos2);
        registroPagos2.setBounds(0, 100, 220, 60);

        registroPagos_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/CrearUsuario.jpg"))); // NOI18N
        registroPagos_img.setMaximumSize(new java.awt.Dimension(65, 65));
        registroPagos_img.setMinimumSize(new java.awt.Dimension(65, 65));
        registroPagos_img.setPreferredSize(new java.awt.Dimension(65, 65));
        registroPagos.add(registroPagos_img);
        registroPagos_img.setBounds(0, 0, 220, 140);

        javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registroPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(crearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(crearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelCentroLayout.setVerticalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(registroPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelCentro);
        panelCentro.setBounds(0, 100, 802, 480);

        panelDerecho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        getContentPane().add(panelDerecho);
        panelDerecho.setBounds(802, 101, 222, 801);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        perfil.setForeground(new Color(242,229,46));
        perfil.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_perfilMouseEntered

    private void perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseExited
        perfil.setForeground(Color.white);
    }//GEN-LAST:event_perfilMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(242,229,46));
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseExited

    private void CrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseEntered
        CrearUsuario.setForeground(new Color(41,135,217));
        CrearUsuario.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CrearUsuarioMouseEntered

    private void CrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseExited
        CrearUsuario.setForeground(Color.black);
    }//GEN-LAST:event_CrearUsuarioMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void CrearClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseEntered
        CrearCliente.setForeground(new Color(41,135,217));
        CrearCliente.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CrearClienteMouseEntered

    private void CrearClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseExited
        CrearCliente.setForeground(Color.black);
    }//GEN-LAST:event_CrearClienteMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        menu_controller.logOut(this);
    }//GEN-LAST:event_logoutMouseClicked

    private void goToProfile(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToProfile
        // TODO add your handling code here:
        menu_controller.goToProfile(this, usuario);
    }//GEN-LAST:event_goToProfile

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        menu_controller.goToRegisterUser(this, usuario);
    }//GEN-LAST:event_CrearUsuarioMouseClicked

    private void CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseClicked
        menu_controller.goToRegisterClient(this, usuario);
    }//GEN-LAST:event_CrearClienteMouseClicked

    private void ListaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseClicked
        menu_controller.goToListClients(this, usuario);
    }//GEN-LAST:event_ListaDeClientesMouseClicked

    private void ListaDeClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseEntered
        ListaDeClientes.setForeground(new Color(41,135,217));
        ListaDeClientes.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ListaDeClientesMouseEntered

    private void ListaDeClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesMouseExited
        ListaDeClientes.setForeground(Color.black);
    }//GEN-LAST:event_ListaDeClientesMouseExited

    private void registroDePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseClicked
        //menu_controller.goToListUsers(this, usuario);
    }//GEN-LAST:event_registroDePagosMouseClicked

    private void registroDePagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseEntered
        registroDePagos.setForeground(new Color(41,135,217));
        registroDePagos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registroDePagosMouseEntered

    private void registroDePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroDePagosMouseExited
        registroDePagos.setForeground(Color.black);
    }//GEN-LAST:event_registroDePagosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrearCliente;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JLabel ListaDeClientes;
    private javax.swing.JLabel back;
    private javax.swing.JPanel crearCliente;
    private javax.swing.JPanel crearCliente2;
    private javax.swing.JLabel crearCliente_img;
    private javax.swing.JPanel crearUsuario;
    private javax.swing.JPanel crearUsuario2;
    private javax.swing.JLabel crearUsuario_img;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelProfileImage;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel listaClientes;
    private javax.swing.JPanel listaClientes2;
    private javax.swing.JLabel listaClientes_img;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JLabel perfil;
    private javax.swing.JLabel registroDePagos;
    private javax.swing.JPanel registroPagos;
    private javax.swing.JPanel registroPagos2;
    private javax.swing.JLabel registroPagos_img;
    private javax.swing.JLabel textoCrearCliente;
    private javax.swing.JLabel textoCrearUsuario;
    private javax.swing.JLabel textoListaClientes;
    private javax.swing.JLabel textoRegistroPagos;
    // End of variables declaration//GEN-END:variables
}
